export const MAKE_REQUEST='MINUTE_MAKE_REQUEST'
export const FAIL_REQUEST='MINUTE_FAIL_REQUEST'
export const CREATE_MINUTE_RESPONSE='CREATE_MINUTE_RESPONSE'
export const SET_FINAL_MINUTES_DATA="SET_FINAL_MINUTES_DATA"
