export const MAKE_REQUEST='MAKE_REQUEST'
export const FAIL_REQUEST='FAIL_REQUEST'
export const OTP_SENT='OTP_SENT'
export const UPDATE_ISSUCCESS='UPDATE_ISSUCCESS'
export const OTP_VERIFIED='OTP_VERIFIED'

