export const MAKE_REQUEST='MEETING_MAKE_REQUEST'
export const FAIL_REQUEST='MEETING_FAIL_REQUEST'
export const GET_MEETING_LIST="GET_MEETING_LIST";
export const GET_ATTENDEES_LIST="GET_ATTENDEES_LIST"
export const UPDATE_RSVP="UPDATE_RSVP"
export const MAKE_RSVP_UPDATE_REQUEST="MAKE_RSVP_UPDATE_REQUEST"