export const MAKE_REQUEST = "MEETING_MAKE_REQUEST";
export const FAIL_REQUEST = "MEETING_FAIL_REQUEST";
export const GET_MEETING_LIST = "GET_MEETING_LIST";
export const GET_ATTENDEES_LIST = "GET_ATTENDEES_LIST";
export const UPDATE_RSVP = "UPDATE_RSVP";
export const MAKE_RSVP_UPDATE_REQUEST = "MAKE_RSVP_UPDATE_REQUEST";
export const CREATE_MEETING_RESPONSE = "CREATE_MEETING_RESPONSE";
export const GET_CREATE_MEETING_STEPS = "GET_CREATE_MEETING_STEPS";
export const UPDATE_ISCREATE_MEETING_PROCESSED =
  "UPDATE_ISCREATE_MEETING_PROCESSED";
export const SET_ATTENDEES = "SET_ATTENDEES";
export const LOAD_PREVIOUS_STEP = "LOAD_PREVIOUS_STEP";
export const UPDATE_MEETING_RESPONSE = "UPDATE_MEETING_RESPONSE";
export const SET_SINGLE_MEETING_DETAILS = "SET_SINGLE_MEETING_DETAILS";
export const SET_MEETING_VIEW_PAGE = "SET_MEETING_VIEW_PAGE";
export const SET_CREATE_NEW_MEETING_PAGE="SET_CREATE_NEW_MEETING_PAGE"
